version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data
    volumes:
      - s3_data:/data

  nodejs-app:
    build: .
    container_name: nodejs-app
    ports:
      - "3000:3000"
    depends_on:
      - minio
    environment:
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      AWS_REGION: us-east-1
      S3_ENDPOINT: http://minio:9000

  s3_service:
    image: minio/minio:latest
    container_name: s3_servicee
    ports:
      - "9001:9000"  # MinIO server
      - "9002:9001"  # MinIO console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - s3_data:/data
    command: server /data --console-address ":9001"

volumes:
  s3_data:
